NumPy Practice



In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
          [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[10,11,12],
           [13,14,15],
           [16,17,18]]])

In [ ]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

In [ ]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

In [ ]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

In [ ]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

In [ ]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
range_array_2 = np.random.randint(10, size=(7,2))
range_array_2

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4,6))

In [17]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
range_array_3 = np.random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(range_array_3)

array([1, 2, 3, 4, 5, 7, 9])

In [18]:
# Find the 0'th index of the latest array you created
range_array_3[0]

array([9, 1, 3, 7, 4, 9, 3])

In [19]:
# Get the first 2 rows of latest array you created
range_array_3[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [20]:
# Get the first 2 values of the first 2 rows of the latest array
range_array_3[:2, :2]

array([[9, 1],
       [5, 3]])

In [21]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a4 = np.random.randint(0,10,size=(3,5))
ones_2 = np.ones((3,5))

In [22]:
# Add the two arrays together
a4 + ones_2

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [23]:
# Create another array of ones of shape (5, 3)
ones_3 = np.ones((5,3))

In [24]:
# Try add the array of ones and the other most recent array together
a4 + ones_3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

Its an error, because shape doesn't match!

In [25]:
# Create another array of ones of shape (3, 5)
ones_4 = np.ones((3,5))

In [27]:
# Subtract the new array of ones from the other most recent array
a4 - ones_4

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [28]:
# Multiply the ones array with the latest array
a4 * ones_4

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [29]:
# Take the latest array to the power of 2 using '**'
a4 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [30]:
# Do the same thing with np.square()
np.square(a4)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [31]:
# Find the mean of the latest array using np.mean()
np.mean(a4)

3.8666666666666667

In [34]:
# Find the maximum of the latest array using np.max()
np.max(a4)

9

In [35]:
# Find the minimum of the latest array using np.min()
np.min(a4)

0

In [36]:
# Find the standard deviation of the latest array
np.std(a4)

2.578543947441829

In [37]:
# Find the variance of the latest array
np.var(a4)

6.648888888888889

In [39]:
# Reshape the latest array to (3, 5, 1)
a4.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [40]:
# Transpose the latest array
a4.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

In [41]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(0,10, size=(3,3))
mat2 = np.random.randint(0,10, size=(3,2))

In [42]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1,mat2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [43]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3 = np.random.randint(0,10,size=(4,3))
mat4 = np.random.randint(0,10,size=(4,3))

In [44]:
# Perform a dot product on the two newest arrays you created
np.dot(mat3,mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. Because the column of mat3 != row of mat4

In [45]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(mat3, mat4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

In [47]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
mat5 = np.random.randint(0,10,size=(3,2))
mat6 = np.random.randint(0,10,size=(3,2))

In [49]:
# Compare the two arrays with '>'
mat5 > mat6

array([[False, False],
       [ True, False],
       [ True,  True]])

In [50]:
# Compare the two arrays with '>='
mat5 >= mat6

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [51]:
# Find which elements of the first array are greater than 7
mat5 > 7

array([[False, False],
       [ True, False],
       [False,  True]])

In [52]:
# Which parts of each array are equal? (try using '==')
mat5 == mat6

array([[False, False],
       [False,  True],
       [False, False]])

In [53]:
# Sort one of the arrays you just created in ascending order
np.sort(mat6)

array([[9, 9],
       [2, 6],
       [0, 3]])

In [55]:
# Sort the indexes of one of the arrays you just created
np.argsort(mat6)

array([[0, 1],
       [0, 1],
       [0, 1]], dtype=int64)

In [56]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(mat6)

0

In [57]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(mat6)

4

In [58]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(mat6, axis=1)

array([0, 1, 1], dtype=int64)

In [59]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(mat6, axis=0)

array([0, 0], dtype=int64)

In [61]:
# Create an array of normally distributed random numbers
np.random.randn(5,6)

array([[-0.21432448, -0.68919421,  0.72783311, -0.61906936,  0.35615983,
        -0.02188087],
       [ 1.21805044, -0.38945802, -0.44280234,  0.37822661,  1.9338398 ,
         0.08097081],
       [-0.41645636,  0.85750325,  0.71812828, -0.95147175, -0.5361601 ,
         1.09652886],
       [ 0.42801284, -2.46969887,  0.48197914,  0.92645636, -0.83758139,
         0.67718607],
       [ 1.87231912,  0.39637394, -0.6256163 , -0.52246148,  0.0130339 ,
         0.37776959]])

In [62]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])